2023-04-23 10:06:58,034 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:06:58,034 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:07:31,800 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:07:31,800 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:07:57,989 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:07:57,989 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:10:15,591 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:10:15,591 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:10:39,903 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:10:39,904 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:45:13,740 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:45:13,740 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:46:29,547 INFO 127.0.0.1 - - [23/Apr/2023 10:46:29] "GET /116/login HTTP/1.1" 200 -
2023-04-23 10:46:33,561 INFO 127.0.0.1 - - [23/Apr/2023 10:46:33] "[32mGET /116 HTTP/1.1[0m" 302 -
2023-04-23 10:46:34,235 INFO 127.0.0.1 - - [23/Apr/2023 10:46:34] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 10:46:34,400 INFO 127.0.0.1 - - [23/Apr/2023 10:46:34] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 10:46:34,404 INFO 127.0.0.1 - - [23/Apr/2023 10:46:34] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 10:46:49,469 INFO 127.0.0.1 - - [23/Apr/2023 10:46:49] "GET /116/new HTTP/1.1" 200 -
2023-04-23 10:47:30,745 INFO –ù–æ–≤–æ–µ –¥–∑ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É –ò—Å—Ç–æ—Ä–∏—è –≤ 9–í –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª @abra
2023-04-23 10:47:30,747 INFO 127.0.0.1 - - [23/Apr/2023 10:47:30] "POST /116/new HTTP/1.1" 200 -
2023-04-23 10:47:35,363 INFO 127.0.0.1 - - [23/Apr/2023 10:47:35] "[32mGET /116 HTTP/1.1[0m" 302 -
2023-04-23 10:47:35,606 INFO 127.0.0.1 - - [23/Apr/2023 10:47:35] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 10:47:35,645 INFO 127.0.0.1 - - [23/Apr/2023 10:47:35] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 10:47:35,652 INFO 127.0.0.1 - - [23/Apr/2023 10:47:35] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 10:47:35,657 INFO 127.0.0.1 - - [23/Apr/2023 10:47:35] "GET /content/905f1bbdc2f5412bb877171a74cd0130.png HTTP/1.1" 200 -
2023-04-23 10:47:45,097 INFO 127.0.0.1 - - [23/Apr/2023 10:47:45] "GET /116/new HTTP/1.1" 200 -
2023-04-23 10:48:05,208 INFO –ù–æ–≤–æ–µ –¥–∑ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É –ò—Å—Ç–æ—Ä–∏—è –≤ 9–í –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª @abra
2023-04-23 10:48:05,209 INFO 127.0.0.1 - - [23/Apr/2023 10:48:05] "POST /116/new HTTP/1.1" 200 -
2023-04-23 10:49:45,299 INFO 127.0.0.1 - - [23/Apr/2023 10:49:45] "[32mGET /116 HTTP/1.1[0m" 302 -
2023-04-23 10:49:45,727 INFO 127.0.0.1 - - [23/Apr/2023 10:49:45] "GET /116/register HTTP/1.1" 200 -
2023-04-23 10:49:46,494 INFO 127.0.0.1 - - [23/Apr/2023 10:49:46] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2023-04-23 10:49:56,880 INFO 127.0.0.1 - - [23/Apr/2023 10:49:56] "[32mPOST /116/register HTTP/1.1[0m" 302 -
2023-04-23 10:49:57,590 INFO 127.0.0.1 - - [23/Apr/2023 10:49:57] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 10:49:58,134 INFO 127.0.0.1 - - [23/Apr/2023 10:49:58] "GET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1" 200 -
2023-04-23 10:49:58,140 INFO 127.0.0.1 - - [23/Apr/2023 10:49:58] "GET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1" 200 -
2023-04-23 10:49:58,172 INFO 127.0.0.1 - - [23/Apr/2023 10:49:58] "GET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1" 200 -
2023-04-23 10:50:25,040 INFO 127.0.0.1 - - [23/Apr/2023 10:50:25] "GET /116/login HTTP/1.1" 200 -
2023-04-23 10:50:39,204 INFO 127.0.0.1 - - [23/Apr/2023 10:50:39] "[32mPOST /116/login HTTP/1.1[0m" 302 -
2023-04-23 10:50:40,010 INFO 127.0.0.1 - - [23/Apr/2023 10:50:40] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 10:50:40,550 INFO 127.0.0.1 - - [23/Apr/2023 10:50:40] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 10:50:40,558 INFO 127.0.0.1 - - [23/Apr/2023 10:50:40] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 10:50:40,560 INFO 127.0.0.1 - - [23/Apr/2023 10:50:40] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 10:50:47,470 INFO 127.0.0.1 - - [23/Apr/2023 10:50:47] "GET /116/new HTTP/1.1" 200 -
2023-04-23 10:51:31,307 INFO –ù–æ–≤–æ–µ –¥–∑ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É –•–∏–º–∏—è –≤ 9–í –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª @abra
2023-04-23 10:51:31,310 INFO 127.0.0.1 - - [23/Apr/2023 10:51:31] "POST /116/new HTTP/1.1" 200 -
2023-04-23 10:51:41,237 INFO 127.0.0.1 - - [23/Apr/2023 10:51:41] "[32mGET /116 HTTP/1.1[0m" 302 -
2023-04-23 10:51:42,178 INFO 127.0.0.1 - - [23/Apr/2023 10:51:42] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 10:51:42,656 INFO 127.0.0.1 - - [23/Apr/2023 10:51:42] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 10:51:42,660 INFO 127.0.0.1 - - [23/Apr/2023 10:51:42] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 10:51:42,691 INFO 127.0.0.1 - - [23/Apr/2023 10:51:42] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 10:51:42,707 INFO 127.0.0.1 - - [23/Apr/2023 10:51:42] "GET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1" 200 -
2023-04-23 10:51:57,602 INFO 127.0.0.1 - - [23/Apr/2023 10:51:57] "[32mGET /116 HTTP/1.1[0m" 302 -
2023-04-23 10:51:57,867 INFO 127.0.0.1 - - [23/Apr/2023 10:51:57] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 10:51:57,912 INFO 127.0.0.1 - - [23/Apr/2023 10:51:57] "GET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1" 200 -
2023-04-23 10:51:57,916 INFO 127.0.0.1 - - [23/Apr/2023 10:51:57] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 10:51:57,923 INFO 127.0.0.1 - - [23/Apr/2023 10:51:57] "GET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1" 200 -
2023-04-23 10:51:57,925 INFO 127.0.0.1 - - [23/Apr/2023 10:51:57] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 10:52:08,025 INFO 127.0.0.1 - - [23/Apr/2023 10:52:08] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 10:52:08,555 INFO 127.0.0.1 - - [23/Apr/2023 10:52:08] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 10:52:08,564 INFO 127.0.0.1 - - [23/Apr/2023 10:52:08] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 10:52:08,604 INFO 127.0.0.1 - - [23/Apr/2023 10:52:08] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 10:52:08,609 INFO 127.0.0.1 - - [23/Apr/2023 10:52:08] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 10:55:38,716 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:55:38,716 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:56:50,768 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:56:50,768 INFO [33mPress CTRL+C to quit[0m
2023-04-23 10:59:37,527 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 10:59:37,527 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:01:21,545 INFO 127.0.0.1 - - [23/Apr/2023 11:01:21] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 11:01:22,134 INFO 127.0.0.1 - - [23/Apr/2023 11:01:22] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 11:01:22,136 INFO 127.0.0.1 - - [23/Apr/2023 11:01:22] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 11:01:22,138 INFO 127.0.0.1 - - [23/Apr/2023 11:01:22] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 11:01:22,150 INFO 127.0.0.1 - - [23/Apr/2023 11:01:22] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 11:02:12,459 INFO 127.0.0.1 - - [23/Apr/2023 11:02:12] "GET /116/93/alg HTTP/1.1" 200 -
2023-04-23 11:02:13,023 INFO 127.0.0.1 - - [23/Apr/2023 11:02:13] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 11:02:26,877 INFO 127.0.0.1 - - [23/Apr/2023 11:02:26] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 11:02:27,360 INFO 127.0.0.1 - - [23/Apr/2023 11:02:27] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 11:02:27,368 INFO 127.0.0.1 - - [23/Apr/2023 11:02:27] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 11:02:27,369 INFO 127.0.0.1 - - [23/Apr/2023 11:02:27] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 11:02:27,375 INFO 127.0.0.1 - - [23/Apr/2023 11:02:27] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 11:02:38,449 INFO 127.0.0.1 - - [23/Apr/2023 11:02:38] "GET /116/93/info HTTP/1.1" 200 -
2023-04-23 11:14:30,453 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:14:30,453 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:15:18,420 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:15:18,420 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:21:00,339 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:21:00,340 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:21:02,495 INFO Application started
2023-04-23 11:23:24,178 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:23:24,178 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:24:45,714 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:24:45,714 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:26:08,422 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:26:08,422 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:26:10,479 INFO Application started
2023-04-23 11:26:28,892 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 25, in start
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 144, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 11:27:20,402 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:27:20,402 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:27:22,539 INFO Application started
2023-04-23 11:28:02,651 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 17, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 144, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 11:28:12,206 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 17, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 144, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 11:28:45,766 INFO 127.0.0.1 - - [23/Apr/2023 11:28:45] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 11:28:45,867 INFO 127.0.0.1 - - [23/Apr/2023 11:28:45] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 11:28:45,892 INFO 127.0.0.1 - - [23/Apr/2023 11:28:45] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 11:28:45,897 INFO 127.0.0.1 - - [23/Apr/2023 11:28:45] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 11:28:45,899 INFO 127.0.0.1 - - [23/Apr/2023 11:28:45] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 11:31:21,046 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:31:21,046 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:31:23,017 INFO Application started
2023-04-23 11:32:22,633 INFO 127.0.0.1 - - [23/Apr/2023 11:32:22] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:32:30,520 INFO 127.0.0.1 - - [23/Apr/2023 11:32:30] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:32:34,407 INFO 127.0.0.1 - - [23/Apr/2023 11:32:34] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:32:37,906 INFO 127.0.0.1 - - [23/Apr/2023 11:32:37] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:32:41,541 INFO 127.0.0.1 - - [23/Apr/2023 11:32:41] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:32:58,961 INFO 127.0.0.1 - - [23/Apr/2023 11:32:58] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:33:25,188 ERROR Exception on /api/116/alice [POST]
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 40, in alice
    handle_dialog(req, resp)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 67, in handle_dialog
    homework = get_homework(grade, token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
all.db_modules.db_utils.RecordNotFoundError
2023-04-23 11:33:25,198 INFO 127.0.0.1 - - [23/Apr/2023 11:33:25] "[35m[1mPOST /api/116/alice HTTP/1.1[0m" 500 -
2023-04-23 11:34:48,824 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:34:48,824 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:34:50,777 INFO 127.0.0.1 - - [23/Apr/2023 11:34:50] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:34:50,851 INFO Application started
2023-04-23 11:34:54,906 INFO 127.0.0.1 - - [23/Apr/2023 11:34:54] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:34:57,261 INFO 127.0.0.1 - - [23/Apr/2023 11:34:57] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:35:00,394 INFO 127.0.0.1 - - [23/Apr/2023 11:35:00] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:35:03,337 INFO 127.0.0.1 - - [23/Apr/2023 11:35:03] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:35:32,849 INFO 127.0.0.1 - - [23/Apr/2023 11:35:32] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:35:56,313 INFO 127.0.0.1 - - [23/Apr/2023 11:35:56] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:36:09,952 INFO 127.0.0.1 - - [23/Apr/2023 11:36:09] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:36:22,413 INFO 127.0.0.1 - - [23/Apr/2023 11:36:22] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:36:34,926 INFO 127.0.0.1 - - [23/Apr/2023 11:36:34] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:38:42,228 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:38:42,228 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:38:44,152 INFO 127.0.0.1 - - [23/Apr/2023 11:38:44] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:38:44,373 INFO Application started
2023-04-23 11:38:52,785 INFO 127.0.0.1 - - [23/Apr/2023 11:38:52] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:39:40,259 INFO 127.0.0.1 - - [23/Apr/2023 11:39:40] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:39:54,777 INFO 127.0.0.1 - - [23/Apr/2023 11:39:54] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:40:16,264 INFO 127.0.0.1 - - [23/Apr/2023 11:40:16] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:40:26,298 INFO 127.0.0.1 - - [23/Apr/2023 11:40:26] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:40:50,226 INFO 127.0.0.1 - - [23/Apr/2023 11:40:50] "GET /116/93/info HTTP/1.1" 200 -
2023-04-23 11:40:53,878 INFO 127.0.0.1 - - [23/Apr/2023 11:40:53] "GET /116/login HTTP/1.1" 200 -
2023-04-23 11:40:59,431 INFO 127.0.0.1 - - [23/Apr/2023 11:40:59] "[32mPOST /116/login HTTP/1.1[0m" 302 -
2023-04-23 11:41:00,330 INFO 127.0.0.1 - - [23/Apr/2023 11:41:00] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 11:41:01,093 INFO 127.0.0.1 - - [23/Apr/2023 11:41:01] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 11:41:01,099 INFO 127.0.0.1 - - [23/Apr/2023 11:41:01] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 11:41:01,102 INFO 127.0.0.1 - - [23/Apr/2023 11:41:01] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 11:41:01,115 INFO 127.0.0.1 - - [23/Apr/2023 11:41:01] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 11:42:50,565 INFO 127.0.0.1 - - [23/Apr/2023 11:42:50] "GET /116/new HTTP/1.1" 200 -
2023-04-23 11:43:34,241 INFO –ù–æ–≤–æ–µ –¥–∑ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É –ë–∏–æ–ª–æ–≥–∏—è –≤ 9–í –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª @abra
2023-04-23 11:43:34,242 INFO 127.0.0.1 - - [23/Apr/2023 11:43:34] "POST /116/new HTTP/1.1" 200 -
2023-04-23 11:43:37,654 INFO 127.0.0.1 - - [23/Apr/2023 11:43:37] "GET /116/new HTTP/1.1" 200 -
2023-04-23 11:43:42,563 INFO 127.0.0.1 - - [23/Apr/2023 11:43:42] "[32mGET /116 HTTP/1.1[0m" 302 -
2023-04-23 11:43:43,459 INFO 127.0.0.1 - - [23/Apr/2023 11:43:43] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 11:43:44,048 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 11:43:44,053 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 11:43:44,114 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "GET /content/28523f2524514d469e66f4183943bdde.png HTTP/1.1" 200 -
2023-04-23 11:43:44,115 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "GET /content/6c38a16440844c6aa1608f14e79e4e02.png HTTP/1.1" 200 -
2023-04-23 11:43:44,142 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 11:43:44,154 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "GET /content/bc6b5982391e4a58ba37f3acfd84c4dd.png HTTP/1.1" 200 -
2023-04-23 11:43:44,158 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 11:43:44,173 INFO 127.0.0.1 - - [23/Apr/2023 11:43:44] "GET /content/991eff89988d4e97b3b624f53f08cb70.png HTTP/1.1" 200 -
2023-04-23 11:44:01,084 INFO 127.0.0.1 - - [23/Apr/2023 11:44:01] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:44:40,269 INFO 127.0.0.1 - - [23/Apr/2023 11:44:40] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:44:46,703 INFO 127.0.0.1 - - [23/Apr/2023 11:44:46] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:45:24,863 INFO 127.0.0.1 - - [23/Apr/2023 11:45:24] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:45:31,532 INFO 127.0.0.1 - - [23/Apr/2023 11:45:31] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:47:30,666 INFO Application started
2023-04-23 11:47:57,843 INFO Application started
2023-04-23 11:55:23,041 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:55:23,041 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:55:25,351 INFO Application started
2023-04-23 11:55:29,744 INFO 127.0.0.1 - - [23/Apr/2023 11:55:29] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:55:37,676 INFO 127.0.0.1 - - [23/Apr/2023 11:55:37] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:55:46,136 INFO 127.0.0.1 - - [23/Apr/2023 11:55:46] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:55:55,564 ERROR Exception on /api/116/alice [POST]
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 40, in alice
    handle_dialog(req, resp)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 79, in handle_dialog
    grade.name_to_id(str(number) + letter)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\data\grades.py", line 36, in name_to_id
    self.id = int(name[0]) * 10 + RETRANSFORMER[name[1].upper()]
                                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: '1'
2023-04-23 11:55:55,574 INFO 127.0.0.1 - - [23/Apr/2023 11:55:55] "[35m[1mPOST /api/116/alice HTTP/1.1[0m" 500 -
2023-04-23 11:57:06,343 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 11:57:06,343 INFO [33mPress CTRL+C to quit[0m
2023-04-23 11:57:08,433 INFO Application started
2023-04-23 11:57:08,766 INFO 127.0.0.1 - - [23/Apr/2023 11:57:08] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 11:57:18,221 ERROR Exception on /api/116/alice [POST]
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 40, in alice
    handle_dialog(req, resp)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 79, in handle_dialog
    grade.name_to_id(str(number) + letter)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\data\grades.py", line 36, in name_to_id
    self.id = int(name[0]) * 10 + RETRANSFORMER[name[1].upper()]
                                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: '1'
2023-04-23 11:57:18,231 INFO 127.0.0.1 - - [23/Apr/2023 11:57:18] "[35m[1mPOST /api/116/alice HTTP/1.1[0m" 500 -
2023-04-23 12:01:38,007 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 12:01:38,007 INFO [33mPress CTRL+C to quit[0m
2023-04-23 12:01:40,030 INFO Application started
2023-04-23 12:01:40,287 INFO 127.0.0.1 - - [23/Apr/2023 12:01:40] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:01:46,294 INFO 127.0.0.1 - - [23/Apr/2023 12:01:46] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:01:50,074 INFO 127.0.0.1 - - [23/Apr/2023 12:01:50] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:01:53,174 INFO 127.0.0.1 - - [23/Apr/2023 12:01:53] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:01:56,896 INFO 127.0.0.1 - - [23/Apr/2023 12:01:56] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:02:00,242 INFO 127.0.0.1 - - [23/Apr/2023 12:02:00] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:02:25,845 INFO 127.0.0.1 - - [23/Apr/2023 12:02:25] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:03:06,754 INFO 127.0.0.1 - - [23/Apr/2023 12:03:06] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:03:22,590 INFO 127.0.0.1 - - [23/Apr/2023 12:03:22] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:03:25,452 INFO 127.0.0.1 - - [23/Apr/2023 12:03:25] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:03:27,981 INFO 127.0.0.1 - - [23/Apr/2023 12:03:27] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:03:30,726 INFO 127.0.0.1 - - [23/Apr/2023 12:03:30] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:06:11,774 INFO 127.0.0.1 - - [23/Apr/2023 12:06:11] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:06:16,903 INFO 127.0.0.1 - - [23/Apr/2023 12:06:16] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:06:24,399 INFO 127.0.0.1 - - [23/Apr/2023 12:06:24] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:06:27,571 INFO 127.0.0.1 - - [23/Apr/2023 12:06:27] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:06:31,429 INFO 127.0.0.1 - - [23/Apr/2023 12:06:31] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:06:34,705 INFO 127.0.0.1 - - [23/Apr/2023 12:06:34] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:07:35,794 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 12:07:35,794 INFO [33mPress CTRL+C to quit[0m
2023-04-23 12:07:37,940 INFO Application started
2023-04-23 12:07:39,411 INFO 127.0.0.1 - - [23/Apr/2023 12:07:39] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:20,749 INFO 127.0.0.1 - - [23/Apr/2023 12:08:20] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:23,975 INFO 127.0.0.1 - - [23/Apr/2023 12:08:23] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:27,173 INFO 127.0.0.1 - - [23/Apr/2023 12:08:27] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:30,416 INFO 127.0.0.1 - - [23/Apr/2023 12:08:30] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:38,973 INFO 127.0.0.1 - - [23/Apr/2023 12:08:38] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:41,341 INFO 127.0.0.1 - - [23/Apr/2023 12:08:41] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:44,039 INFO 127.0.0.1 - - [23/Apr/2023 12:08:44] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:47,337 INFO 127.0.0.1 - - [23/Apr/2023 12:08:47] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:55,801 INFO 127.0.0.1 - - [23/Apr/2023 12:08:55] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:08:58,358 INFO 127.0.0.1 - - [23/Apr/2023 12:08:58] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:09:01,479 INFO 127.0.0.1 - - [23/Apr/2023 12:09:01] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:09:03,980 INFO –ù–æ–≤—ã–π –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å 1BD290C64609F1FEF8091BEEEEB64E0D62B6948C516F6D5E862BE2284360CBE1 –≤ 3–ê –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–ª—Å—è
2023-04-23 12:09:04,004 INFO 127.0.0.1 - - [23/Apr/2023 12:09:04] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:09:17,543 INFO 127.0.0.1 - - [23/Apr/2023 12:09:17] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 12:11:40,826 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 12:11:40,826 INFO [33mPress CTRL+C to quit[0m
2023-04-23 12:11:42,840 INFO Application started
2023-04-23 12:11:43,002 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 17, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 12:11:43,144 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 12:11:43,716 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 12:11:43,790 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 12:11:43,868 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 12:11:43,881 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 12:11:43,888 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/28523f2524514d469e66f4183943bdde.png HTTP/1.1[0m" 304 -
2023-04-23 12:11:43,895 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/991eff89988d4e97b3b624f53f08cb70.png HTTP/1.1[0m" 304 -
2023-04-23 12:11:43,897 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/bc6b5982391e4a58ba37f3acfd84c4dd.png HTTP/1.1[0m" 304 -
2023-04-23 12:11:43,898 INFO 127.0.0.1 - - [23/Apr/2023 12:11:43] "[36mGET /content/6c38a16440844c6aa1608f14e79e4e02.png HTTP/1.1[0m" 304 -
2023-04-23 12:12:17,648 INFO 127.0.0.1 - - [23/Apr/2023 12:12:17] "GET /116/new HTTP/1.1" 200 -
2023-04-23 12:12:47,119 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 17, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 13:01:51,389 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 13:01:51,389 INFO [33mPress CTRL+C to quit[0m
2023-04-23 13:01:53,561 INFO Application started
2023-04-23 13:02:04,014 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 13:02:04,659 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 13:02:04,673 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 13:02:04,723 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/6c38a16440844c6aa1608f14e79e4e02.png HTTP/1.1[0m" 304 -
2023-04-23 13:02:04,725 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/28523f2524514d469e66f4183943bdde.png HTTP/1.1[0m" 304 -
2023-04-23 13:02:04,767 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 13:02:04,773 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/bc6b5982391e4a58ba37f3acfd84c4dd.png HTTP/1.1[0m" 304 -
2023-04-23 13:02:04,778 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/991eff89988d4e97b3b624f53f08cb70.png HTTP/1.1[0m" 304 -
2023-04-23 13:02:04,779 INFO 127.0.0.1 - - [23/Apr/2023 13:02:04] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 13:12:18,457 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 13:12:18,457 INFO [33mPress CTRL+C to quit[0m
2023-04-23 13:12:20,373 INFO 127.0.0.1 - - [23/Apr/2023 13:12:20] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:12:20,701 INFO Application started
2023-04-23 13:12:32,670 INFO 127.0.0.1 - - [23/Apr/2023 13:12:32] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:12:44,966 INFO 127.0.0.1 - - [23/Apr/2023 13:12:44] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:13:04,355 INFO 127.0.0.1 - - [23/Apr/2023 13:13:04] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:13:11,168 INFO 127.0.0.1 - - [23/Apr/2023 13:13:11] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:13:14,202 ERROR Exception on /api/116/alice [POST]
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 40, in alice
    handle_dialog(req, resp)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 116, in handle_dialog
    add_user(user_id, grade, group)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 220, in add_user
    raise RecordNotFoundError
all.db_modules.db_utils.RecordNotFoundError
2023-04-23 13:13:14,213 INFO 127.0.0.1 - - [23/Apr/2023 13:13:14] "[35m[1mPOST /api/116/alice HTTP/1.1[0m" 500 -
2023-04-23 13:13:50,372 INFO 127.0.0.1 - - [23/Apr/2023 13:13:50] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:13:54,518 INFO 127.0.0.1 - - [23/Apr/2023 13:13:54] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:13:57,304 INFO 127.0.0.1 - - [23/Apr/2023 13:13:57] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:14:02,851 INFO 127.0.0.1 - - [23/Apr/2023 13:14:02] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:14:05,498 ERROR Exception on /api/116/alice [POST]
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 40, in alice
    handle_dialog(req, resp)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\alice.py", line 116, in handle_dialog
    add_user(user_id, grade, group)
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 220, in add_user
    raise RecordNotFoundError
all.db_modules.db_utils.RecordNotFoundError
2023-04-23 13:14:05,501 INFO 127.0.0.1 - - [23/Apr/2023 13:14:05] "[35m[1mPOST /api/116/alice HTTP/1.1[0m" 500 -
2023-04-23 13:15:55,533 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 13:15:55,533 INFO [33mPress CTRL+C to quit[0m
2023-04-23 13:15:57,727 INFO Application started
2023-04-23 13:15:57,921 INFO 127.0.0.1 - - [23/Apr/2023 13:15:57] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:16:02,574 INFO 127.0.0.1 - - [23/Apr/2023 13:16:02] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:16:07,711 INFO 127.0.0.1 - - [23/Apr/2023 13:16:07] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:16:45,781 INFO 127.0.0.1 - - [23/Apr/2023 13:16:45] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:17:36,295 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 13:17:36,295 INFO [33mPress CTRL+C to quit[0m
2023-04-23 13:17:38,266 INFO Application started
2023-04-23 13:17:41,214 INFO 127.0.0.1 - - [23/Apr/2023 13:17:41] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:17:45,517 INFO 127.0.0.1 - - [23/Apr/2023 13:17:45] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:17:49,751 INFO 127.0.0.1 - - [23/Apr/2023 13:17:49] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:17:58,754 INFO 127.0.0.1 - - [23/Apr/2023 13:17:58] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:18:06,247 INFO 127.0.0.1 - - [23/Apr/2023 13:18:06] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:18:17,788 INFO 127.0.0.1 - - [23/Apr/2023 13:18:17] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:18:21,449 INFO 127.0.0.1 - - [23/Apr/2023 13:18:21] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:18:24,358 INFO 127.0.0.1 - - [23/Apr/2023 13:18:24] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:18:27,220 INFO 127.0.0.1 - - [23/Apr/2023 13:18:27] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:18:31,863 INFO –ù–æ–≤—ã–π –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å 1BD290C64609F1FEF8091BEEEEB64E0D62B6948C516F6D5E862BE2284360CBE1 –≤ 9–í –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–ª—Å—è
2023-04-23 13:18:31,879 INFO 127.0.0.1 - - [23/Apr/2023 13:18:31] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:18:43,343 INFO 127.0.0.1 - - [23/Apr/2023 13:18:43] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 13:26:19,552 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 17, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 13:49:14,279 INFO Application started
2023-04-23 13:49:44,418 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 23, in start
    await update.bot.send_message('alg')
          ^^^^^^^^^^
AttributeError: 'Update' object has no attribute 'bot'
2023-04-23 13:52:31,619 INFO Application started
2023-04-23 13:52:35,048 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 24, in start
    await update.bot.send_message('alg')
          ^^^^^^^^^^
AttributeError: 'Update' object has no attribute 'bot'
2023-04-23 13:53:03,194 INFO Application started
2023-04-23 13:53:08,967 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 24, in start
    await context.bot.send_message('@alex010407', '–ö–æ—à–∫–∞')
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found
2023-04-23 13:55:21,324 INFO Application started
2023-04-23 13:56:49,366 INFO Application started
2023-04-23 13:57:16,698 INFO Application started
2023-04-23 14:01:58,495 INFO Application started
2023-04-23 14:02:11,510 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 14:04:24,274 INFO Application started
2023-04-23 14:04:30,000 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 14:05:04,352 INFO Application started
2023-04-23 14:05:18,886 INFO Application started
2023-04-23 14:05:41,594 INFO Application started
2023-04-23 14:07:16,744 INFO Application started
2023-04-23 14:08:31,062 INFO Application started
2023-04-23 14:08:58,178 INFO Application started
2023-04-23 14:09:18,256 INFO Application started
2023-04-23 14:10:06,743 INFO Application started
2023-04-23 14:15:20,745 INFO Application started
2023-04-23 14:40:16,588 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 14:40:16,588 INFO [33mPress CTRL+C to quit[0m
2023-04-23 14:41:20,942 INFO 127.0.0.1 - - [23/Apr/2023 14:41:20] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 14:41:26,675 INFO 127.0.0.1 - - [23/Apr/2023 14:41:26] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 14:41:32,208 INFO 127.0.0.1 - - [23/Apr/2023 14:41:32] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 14:41:37,301 INFO 127.0.0.1 - - [23/Apr/2023 14:41:37] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 14:41:42,766 INFO 127.0.0.1 - - [23/Apr/2023 14:41:42] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 14:41:45,451 INFO –ù–æ–≤—ã–π –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å 1BD290C64609F1FEF8091BEEEEB64E0D62B6948C516F6D5E862BE2284360CBE1 –≤ 9–í –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–ª—Å—è
2023-04-23 14:41:45,480 INFO 127.0.0.1 - - [23/Apr/2023 14:41:45] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 14:41:56,899 INFO 127.0.0.1 - - [23/Apr/2023 14:41:56] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 14:42:37,078 INFO Application started
2023-04-23 15:16:32,901 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8080
2023-04-23 15:16:32,902 INFO [33mPress CTRL+C to quit[0m
2023-04-23 15:16:47,067 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 15:16:47,682 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 15:16:47,684 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 15:16:47,688 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/6c38a16440844c6aa1608f14e79e4e02.png HTTP/1.1[0m" 304 -
2023-04-23 15:16:47,751 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/bc6b5982391e4a58ba37f3acfd84c4dd.png HTTP/1.1[0m" 304 -
2023-04-23 15:16:47,756 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/28523f2524514d469e66f4183943bdde.png HTTP/1.1[0m" 304 -
2023-04-23 15:16:47,761 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/991eff89988d4e97b3b624f53f08cb70.png HTTP/1.1[0m" 304 -
2023-04-23 15:16:47,762 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 15:16:47,766 INFO 127.0.0.1 - - [23/Apr/2023 15:16:47] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 15:17:01,766 INFO 127.0.0.1 - - [23/Apr/2023 15:17:01] "GET /116/new HTTP/1.1" 200 -
2023-04-23 15:18:58,752 INFO –ù–æ–≤–æ–µ –¥–∑ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É –ì–µ–æ–º–µ—Ç—Ä–∏—è –≤ 9–í –æ–ø—É–±–ª–∏–∫–æ–≤–∞–ª @abra
2023-04-23 15:18:58,754 INFO 127.0.0.1 - - [23/Apr/2023 15:18:58] "POST /116/new HTTP/1.1" 200 -
2023-04-23 15:19:08,808 INFO 127.0.0.1 - - [23/Apr/2023 15:19:08] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 15:19:21,141 INFO 127.0.0.1 - - [23/Apr/2023 15:19:21] "POST /api/116/alice HTTP/1.1" 200 -
2023-04-23 15:19:35,178 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "[32mGET /116 HTTP/1.1[0m" 302 -
2023-04-23 15:19:35,629 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "GET /116/93 HTTP/1.1" 200 -
2023-04-23 15:19:35,777 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "[36mGET /content/0ff8668f2bdc4ab19bd76110ea034001.png HTTP/1.1[0m" 304 -
2023-04-23 15:19:35,787 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "[36mGET /content/a0b1b1ef654f4e46b36b5bf458b9a6e1.png HTTP/1.1[0m" 304 -
2023-04-23 15:19:35,795 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "GET /content/6c38a16440844c6aa1608f14e79e4e02.png HTTP/1.1" 200 -
2023-04-23 15:19:35,802 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "GET /content/28523f2524514d469e66f4183943bdde.png HTTP/1.1" 200 -
2023-04-23 15:19:35,816 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "GET /content/bc6b5982391e4a58ba37f3acfd84c4dd.png HTTP/1.1" 200 -
2023-04-23 15:19:35,817 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "GET /content/991eff89988d4e97b3b624f53f08cb70.png HTTP/1.1" 200 -
2023-04-23 15:19:35,952 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "[36mGET /content/292b2dd49509453fa251e3199eb61b1f.png HTTP/1.1[0m" 304 -
2023-04-23 15:19:35,956 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "[36mGET /content/f07c176b7c7246c09b33e22b22796a6d.png HTTP/1.1[0m" 304 -
2023-04-23 15:19:35,971 INFO 127.0.0.1 - - [23/Apr/2023 15:19:35] "GET /content/38c198816565407294818fb3319e7d27.png HTTP/1.1" 200 -
2023-04-23 15:19:36,077 INFO 127.0.0.1 - - [23/Apr/2023 15:19:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2023-04-23 15:56:31,208 INFO Application started
2023-04-23 15:57:01,224 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 36, in start
    ['6', '7', '8']
TypeError: list indices must be integers or slices, not tuple
2023-04-23 15:57:56,031 INFO Application started
2023-04-23 15:58:03,494 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 29, in start
    ['6', '7', '8']
TypeError: list indices must be integers or slices, not tuple
2023-04-23 15:58:57,209 INFO Application started
2023-04-23 15:58:59,463 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 27, in start
    reply = f'''–°–∞–ª–∞–º–∞–ª–µ–π–∫—É–º, {await update.message.from_user.first_name}!\n–ß—Ç–æ–±—ã –Ω–∞—á–∞—Ç—å —Ä–∞–±–æ—Ç—É, —Å–∫–∞–∂–∏, –≤ –∫–∞–∫–æ–º —Ç—ã –∫–ª–∞—Å—Å–µ? –ö –ø—Ä–∏–º–µ—Ä—É: "–Ø —É—á—É—Å—å –≤ 10–í"'''
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object str can't be used in 'await' expression
2023-04-23 15:59:43,576 INFO Application started
2023-04-23 16:00:05,073 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 27, in start
    reply = f'''–°–∞–ª–∞–º–∞–ª–µ–π–∫—É–º, {await update.message.from_user.first_name}!\n–ß—Ç–æ–±—ã –Ω–∞—á–∞—Ç—å —Ä–∞–±–æ—Ç—É, —Å–∫–∞–∂–∏, –≤ –∫–∞–∫–æ–º —Ç—ã –∫–ª–∞—Å—Å–µ? –ö –ø—Ä–∏–º–µ—Ä—É: "–Ø —É—á—É—Å—å –≤ 10–í"'''
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object str can't be used in 'await' expression
2023-04-23 16:00:17,205 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 16:00:49,727 INFO Application started
2023-04-23 16:01:13,450 INFO Application started
2023-04-23 16:01:23,782 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 16:02:42,989 INFO Application started
2023-04-23 16:02:56,576 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 16:05:58,684 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 16:10:23,609 INFO Application started
2023-04-23 16:10:30,093 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 36, in start
    await update.message.reply_text(reply, reply_markup=reply_markup)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
2023-04-23 16:10:57,679 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 36, in start
    await update.message.reply_text(reply, reply_markup=reply_markup)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
2023-04-23 16:11:00,352 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 36, in start
    await update.message.reply_text(reply, reply_markup=reply_markup)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
2023-04-23 16:13:09,575 INFO Application started
2023-04-23 16:13:14,186 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 34, in start
    await update.message.reply_text(reply, reply_markup=reply_markup)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
2023-04-23 16:13:43,170 INFO Application started
2023-04-23 16:13:47,088 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 34, in start
    await update.message.reply_text(reply, reply_markup=reply_markup)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
2023-04-23 16:15:00,839 INFO Application started
2023-04-23 16:15:07,679 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 34, in start
    await update.message.reply_text(reply, reply_markup=reply_markup)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
2023-04-23 16:16:00,800 INFO Application started
2023-04-23 16:16:52,328 INFO Application started
2023-04-23 16:16:59,785 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 34, in start
    await update.message.reply_text(reply, reply_markup=reply_markup)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
2023-04-23 16:17:55,314 INFO Application started
2023-04-23 16:19:13,847 INFO Application started
2023-04-23 16:21:47,578 INFO Application started
2023-04-23 16:21:55,781 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 16:21:56,071 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 18, in echo
    message = get_homework(93, update.message.text)['text']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\db_modules\db_utils.py", line 145, in get_homework
    raise RecordNotFoundError
db_modules.db_utils.RecordNotFoundError
2023-04-23 16:34:42,474 INFO Application started
2023-04-23 16:34:50,814 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_httpxrequest.py", line 196, in do_request
    data = request_data.json_parameters if request_data else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_requestdata.py", line 73, in json_parameters
    return {
           ^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_requestdata.py", line 76, in <dictcomp>
    if param.json_value is not None
       ^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_requestparameter.py", line 74, in json_value
    return json.dumps(self.value)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InlineKeyboardButton is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 40, in start
    await update.message.reply_text(reply, reply_markup=keyboard)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 290, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {repr(exc)}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: TypeError('Object of type InlineKeyboardButton is not JSON serializable')
2023-04-23 16:35:19,733 INFO Application started
2023-04-23 16:36:01,035 INFO Application started
2023-04-23 16:36:45,763 INFO Application started
2023-04-23 16:37:06,191 INFO Application started
2023-04-23 16:38:06,776 INFO Application started
2023-04-23 16:38:10,664 ERROR No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_httpxrequest.py", line 196, in do_request
    data = request_data.json_parameters if request_data else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_requestdata.py", line 73, in json_parameters
    return {
           ^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_requestdata.py", line 76, in <dictcomp>
    if param.json_value is not None
       ^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_requestparameter.py", line 74, in json_value
    return json.dumps(self.value)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alexs\PythonProjects\AChtoZadano\all\tg_bot.py", line 42, in start
    await update.message.reply_text(reply, reply_markup=ReplyKeyboardRemove)
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_message.py", line 1041, in reply_text
    return await self.get_bot().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 2598, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 760, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 488, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 512, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 419, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\_bot.py", line 450, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 165, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexs\AppData\Roaming\Python\Python311\site-packages\telegram\request\_baserequest.py", line 290, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {repr(exc)}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: TypeError('Object of type type is not JSON serializable')
2023-04-23 16:38:37,714 INFO Application started
2023-04-23 16:39:31,466 INFO Application started
2023-04-23 16:42:19,725 INFO Application started
2023-04-23 16:44:48,142 INFO Application started
2023-04-23 16:45:34,346 INFO Application started
